import { TerminalAnalysisData } from "@/types/analysis";

/**
 * Deterministic number formatter for USD currency and quantities.
 * Replaces locale-dependent toLocaleString() to prevent SSR/Hydration mismatches in Next.js.
 */
export function formatNumber(val: number): string {
  const rounded = Math.round(val);
  const isNeg = rounded < 0;
  const absStr = Math.abs(rounded).toString();
  const formatted = absStr.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return isNeg ? `-${formatted}` : formatted;
}

export const MOCK_ANALYSIS_DATA: TerminalAnalysisData = {
  event: {
    id: "EVT-2026-0941",
    type: "HURRICANE",
    name: "Hurricane Alpha",
    category: "CATEGORY 4 HURRICANE",
    severity: 0.91,
    location: "Gulf of Mexico",
    headline: "CATEGORY 4 HURRICANE — GULF OF MEXICO",
    summary:
      "Rapidly intensifying system sustained at 135 mph heading toward major offshore production corridors. Expected landfall within 36 hours.",
    timestamp: "2026-10-03T11:45:00Z",
    affected_sector: "ENERGY",
    status: "ACTIVE_TRACKING",
  },

  weather: {
    severity_score: 0.91,
    max_wind_speed_mph: 135,
    central_pressure_mb: 938,
    storm_surge_ft: 14.5,
    projected_landfall: "Port Fourchon / Central Gulf Coast (T-34h)",
    offshore_platforms_threatened: 142,
    status: "CRITICAL_PATH",
    source: "NOAA National Hurricane Center Feed",
  },

  news: {
    sentiment: -0.72,
    sentiment_label: "BEARISH",
    article_count: 18,
    top_headlines: [
      {
        title: "BSEE confirms precautionary shut-in of 34% Gulf oil production",
        source: "Reuters Energy",
        time_ago: "28m ago",
        sentiment: -0.84,
      },
      {
        title: "Refinery corridor along Louisiana coast issues mandatory evacuations",
        source: "Bloomberg Terminal",
        time_ago: "1h ago",
        sentiment: -0.76,
      },
      {
        title: "Offshore platform crews airlifted as Category 4 storm accelerates",
        source: "Argus Media",
        time_ago: "2h ago",
        sentiment: -0.68,
      },
    ],
    urgency: "HIGH",
  },

  market: {
    energy_sector_movement: -0.038,
    crude_oil_movement: 0.042,
    sp500_movement: -0.0065,
    sector_performance: {
      Energy: -0.038,
      Technology: 0.004,
      Utilities: -0.012,
      Financials: -0.005,
    },
    vix_level: 21.4,
    vix_change_pct: 0.088,
  },

  historical: {
    similar_events: 7,
    median_impact: -0.058,
    mean_impact: -0.062,
    max_drawdown: -0.114,
    recovery_days_median: 14,
    key_analogs: [
      {
        name: "Hurricane Ida",
        year: 2021,
        category: 4,
        impact_pct: -0.064,
        recovery_days: 12,
      },
      {
        name: "Hurricane Katrina",
        year: 2005,
        category: 5,
        impact_pct: -0.114,
        recovery_days: 28,
      },
      {
        name: "Hurricane Laura",
        year: 2020,
        category: 4,
        impact_pct: -0.048,
        recovery_days: 9,
      },
      {
        name: "Hurricane Harvey",
        year: 2017,
        category: 4,
        impact_pct: -0.058,
        recovery_days: 16,
      },
      {
        name: "Hurricane Rita",
        year: 2005,
        category: 3,
        impact_pct: -0.052,
        recovery_days: 11,
      },
      {
        name: "Hurricane Michael",
        year: 2018,
        category: 5,
        impact_pct: -0.042,
        recovery_days: 8,
      },
      {
        name: "Hurricane Ike",
        year: 2008,
        category: 2,
        impact_pct: -0.056,
        recovery_days: 14,
      },
    ],
  },

  risk: {
    risk_score: 60.15,
    risk_level: "HIGH",
    confidence: 1.0,
    portfolio_impact: -0.0284,
    estimated_dollar_loss: -27800,
    portfolio_total_value: 980000,
    energy_exposure_pct: 0.49,
    technology_exposure_pct: 0.51,
    audit_factors: [
      {
        factor: "Energy Sector Exposure",
        weight: "49.0%",
        value: "49.0% total allocation",
        direction: "NEGATIVE",
        detail: "Concentration in offshore Gulf producers elevates vulnerability above the 25% institutional risk threshold.",
      },
      {
        factor: "Meteorological Severity",
        weight: "91.0%",
        value: "Cat 4 / 91% severe",
        direction: "NEGATIVE",
        detail: "Sustained wind velocity and trajectory match critical infrastructure destruction thresholds.",
      },
      {
        factor: "Historical Median Drawdown",
        weight: "-5.8%",
        value: "-5.80% across 7 analogs",
        direction: "NEGATIVE",
        detail: "7 historical Gulf Category 4+ hurricanes produced an average drawdown of -5.8% across impacted assets.",
      },
      {
        factor: "News & Disruption Sentiment",
        weight: "-0.72",
        value: "-0.72 score (18 feeds)",
        direction: "NEGATIVE",
        detail: "Confirmed production shut-ins and emergency staff evacuations across major offshore operators.",
      },
      {
        factor: "Real-time Market Movement",
        weight: "-3.8%",
        value: "-3.80% intraday energy drag",
        direction: "NEGATIVE",
        detail: "Intraday energy sector index divergence against benchmark equity indices.",
      },
    ],
  },

  scenarios: {
    mild: -0.0098,
    base: -0.0284,
    severe: -0.0466,
    breakdown: [
      {
        id: "mild",
        name: "MILD",
        impact_pct: -0.0098,
        dollar_loss: -9604,
        projected_value: 970396,
        description: "Path deflects east of primary offshore production assets; precautionary shut-ins reverse within 48h.",
        probability: 0.2,
      },
      {
        id: "base",
        name: "BASE",
        impact_pct: -0.0284,
        dollar_loss: -27832,
        projected_value: 952168,
        description: "Direct tracking across Mississippi Canyon corridor; localized infrastructure damage with 10-14 day restart delay.",
        probability: 0.55,
      },
      {
        id: "severe",
        name: "SEVERE",
        impact_pct: -0.0466,
        dollar_loss: -45668,
        projected_value: 934332,
        description: "Category escalation with protracted refinery outage and deepwater pipeline connection ruptures.",
        probability: 0.25,
      },
    ],
  },

  portfolio: {
    total_value: 980000,
    sectors: [
      {
        sector: "Energy",
        allocation_pct: 49.0,
        value: 480200,
        is_affected: true,
      },
      {
        sector: "Technology",
        allocation_pct: 51.0,
        value: 499800,
        is_affected: false,
      },
    ],
    top_risk_contributors: [
      {
        ticker: "XOM",
        name: "Exxon Mobil Corp.",
        sector: "Energy",
        weight_pct: 25.0,
        current_value: 245000,
        current_price: 114.2,
        estimated_impact_pct: -0.0596,
        estimated_dollar_impact: -14602,
        risk_contribution_pct: 52.5,
        risk_tier: "HIGH",
      },
      {
        ticker: "CVX",
        name: "Chevron Corp.",
        sector: "Energy",
        weight_pct: 18.0,
        current_value: 176400,
        current_price: 148.8,
        estimated_impact_pct: -0.075,
        estimated_dollar_impact: -13230,
        risk_contribution_pct: 47.5,
        risk_tier: "HIGH",
      },
      {
        ticker: "OXY",
        name: "Occidental Petroleum",
        sector: "Energy",
        weight_pct: 6.0,
        current_value: 58800,
        current_price: 52.3,
        estimated_impact_pct: -0.0833,
        estimated_dollar_impact: -4898,
        risk_contribution_pct: 17.6,
        risk_tier: "HIGH",
      },
    ],
  },

  strategy: {
    type: "HEDGE",
    title: "DOWNWARD CONTAGION OVERLAY",
    urgency: "HIGH",
    reason: "High energy concentration (49%) coupled with adverse weather trajectory (91% severity) warrants immediate tactical hedge.",
    hedging_vehicles: [
      "Purchase short-dated XLE put options (30-day expiry, 5% OTM)",
      "Allocate 8% portfolio notional into Brent crude short-term collar",
      "Trim high-beta offshore levered names (OXY) prior to landfall window",
    ],
    recommended_allocation_pct: 8.5,
  },

  agent_trace: [
    {
      id: "tr-01",
      agent_name: "USER QUERY",
      role: "Input Ingestion",
      status: "COMPLETED",
      metric_label: "Prompt Input",
      metric_value: "Cat 4 Hurricane Gulf Risk",
      latency_ms: 12,
      timestamp: "11:45:01.012",
      summary: "Ingested query: Evaluate hurricane risk impact on energy portfolio holdings.",
    },
    {
      id: "tr-02",
      agent_name: "SUPERVISOR",
      role: "LangGraph Router",
      status: "COMPLETED",
      metric_label: "Dispatched",
      metric_value: "3 Parallel Subgraphs",
      latency_ms: 45,
      timestamp: "11:45:01.057",
      summary: "Classified shock event as meteorological/energy. Dispatched weather, news, and market workers.",
    },
    {
      id: "tr-03",
      agent_name: "WEATHER AGENT",
      role: "Environmental Intelligence",
      status: "COMPLETED",
      metric_label: "Severity",
      metric_value: "91% (Cat 4)",
      latency_ms: 420,
      timestamp: "11:45:01.477",
      summary: "Queried NOAA tracking feed. Identified 135mph sustained eyewall traversing Gulf zone.",
    },
    {
      id: "tr-04",
      agent_name: "NEWS AGENT",
      role: "Sentiment & Disruption Scraper",
      status: "COMPLETED",
      metric_label: "Sentiment",
      metric_value: "-0.72 (18 feeds)",
      latency_ms: 680,
      timestamp: "11:45:02.157",
      summary: "Parsed 18 wire bulletins. Extracted 34% shut-in confirmation and evacuation mandates.",
    },
    {
      id: "tr-05",
      agent_name: "HISTORICAL AGENT",
      role: "Analog Retrieval Engine",
      status: "COMPLETED",
      metric_label: "Analogs",
      metric_value: "7 matches",
      latency_ms: 510,
      timestamp: "11:45:02.667",
      summary: "Retrieved 7 comparable hurricanes (Katrina, Ida, Harvey, Laura). Derived median -5.8% drawdown.",
    },
    {
      id: "tr-06",
      agent_name: "RISK ENGINE",
      role: "Quantitative Valuation Engine",
      status: "COMPLETED",
      metric_label: "Risk Score",
      metric_value: "60.15 / 100",
      latency_ms: 120,
      timestamp: "11:45:02.787",
      summary: "Computed asset weights, sector concentration, scenario drawdowns (-0.98% to -4.66%).",
    },
    {
      id: "tr-07",
      agent_name: "STRATEGY AGENT",
      role: "Synthesis & Mitigation",
      status: "COMPLETED",
      metric_label: "Recommendation",
      metric_value: "TACTICAL HEDGE",
      latency_ms: 900,
      timestamp: "11:45:03.687",
      summary: "Synthesized multi-agent inputs. Formulated option collar and exposure reduction advisory.",
    },
  ],

  evidence: [
    {
      id: "ev-01",
      type: "HISTORICAL",
      title: "Historical Event Precedent Cluster",
      source: "Sentry Historical DB (Katrina 2005, Ida 2021, Harvey 2017)",
      timestamp: "2026-10-03T11:45:02Z",
      signal: "7 comparable Gulf Category 4/5 events analyzed; median recovery timeline: 14 trading days.",
      relevance_score: 0.94,
    },
    {
      id: "ev-02",
      type: "NEWS",
      title: "Real-time Wire & Regulatory Shut-In Dispatches",
      source: "Reuters / Bureau of Safety and Environmental Enforcement (BSEE)",
      timestamp: "2026-10-03T11:17:00Z",
      signal: "18 verified reports confirm 34% of Gulf crude production and 28% natural gas shut-in.",
      relevance_score: 0.92,
    },
    {
      id: "ev-03",
      type: "WEATHER",
      title: "NOAA NHC Reconnaissance Advisory #14",
      source: "National Oceanic and Atmospheric Administration",
      timestamp: "2026-10-03T11:30:00Z",
      signal: "Central pressure 938mb, Category 4 forward motion 12kt toward Port Fourchon sector.",
      relevance_score: 0.98,
    },
    {
      id: "ev-04",
      type: "MARKET",
      title: "Intraday Energy Index & Tick Spread Analysis",
      source: "Direct Exchange Liquidity Feed",
      timestamp: "2026-10-03T11:44:30Z",
      signal: "Energy ETF (XLE) -3.8% intraday; front-month WTI crude premium widening to +$3.40/bbl.",
      relevance_score: 0.89,
    },
  ],

  meta: {
    model_version: "SENTRY-QUANT-V2.4",
    engine_latency_ms: 2687,
    is_demo: true,
    computed_at: "2026-10-03T11:45:03Z",
    pipeline_status: "NOMINAL",
  },
};
